"""
stampy datatypes
"""

import galaxy.datatypes.data as data
import logging, os, sys, time, tempfile, shutil, string, glob, re
import galaxy.model
from galaxy.datatypes import metadata
from galaxy.datatypes.metadata import MetadataElement
from galaxy import util
from galaxy.datatypes.binary import Binary
from galaxy.datatypes.sniff import *

log = logging.getLogger(__name__)

class StampyIndex( Binary ):
    """Class describing the index file generated by stampy """

    def sniff( self, filename ):
        """
        Determines whether the file is a Stampy index file
        """
        
        ext = filename.split(".")[-1]
        if ext == "stidx" : 
            return True
        else:
            return False

class StampyHashTable( Binary ):
    """Class describing the HashTable file generated by Stampy """

    def sniff( self, filename ):
        """
        Determines whether the file is a HashTable from Stampy
        """

        ext = filename.split(".")[-1]
        if ext == "sthash" : 
            return True
        else:
            return False


class StampyIndexFiles( data.Text ): # data.Text because of the log file
    composite_type = 'basic'
    allow_datatype_change = False
    file_ext = 'stlog'

    def __init__( self, **kwd ):
        data.Text.__init__( self, **kwd )
        self.add_composite_file( 'prefix.stidx', description = 'StampyIndex component file', optional = False,
                                 substitute_name_with_metadata = None, is_binary = True )
        self.add_composite_file( 'prefix.sthash', description = 'StampyHashTable component file', optional = False, 
                                 substitute_name_with_metadata = None, is_binary = True )



if __name__ == '__main__':
    import doctest, sys
    doctest.testmod(sys.modules[__name__])

